// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using muscatApi.Models;

#nullable disable

namespace muscatApi.Migrations
{
    [DbContext(typeof(muscatApiContext))]
    [Migration("20220309170926_ChangePwdTypeToString")]
    partial class ChangePwdTypeToString
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("muscatApi.Models.MyUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("MyStatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("MyUser");
                });

            modelBuilder.Entity("muscatApi.Models.Pwd", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PWD");
                });

            modelBuilder.Entity("muscatApi.Models.Pwd", b =>
                {
                    b.HasOne("muscatApi.Models.MyUser", "IdNavigation")
                        .WithOne("Pwd")
                        .HasForeignKey("muscatApi.Models.Pwd", "Id")
                        .IsRequired()
                        .HasConstraintName("FK_PWD_MyUser");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("muscatApi.Models.MyUser", b =>
                {
                    b.Navigation("Pwd")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
